version: '3.8'

services:
  backend_service:
    build:
      context: ./backend
    container_name: backend_service
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend_service:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:80"
    restart: unless-stopped
